### ISSUE TITLE
Android apk

### ISSUE THREAD

**Issue by Ho52198** [f4exb/sdrangel#125]
Hello. You can imagine how nice will be to have such app in android. Even simplified or for rooted devices only. There is nithing for dmr for android. Sdrangel can be the first one :)

**Comment by f4exb** [comment]
Well Marty is already active on this. See this (long) topic: https://groups.io/g/sdrangel/topic/issue_when_compiling_sdrangel/7732033

I have tried to port the whole application a long time ago as Qt supposedly supports the Android toolchain. I could get an .apk out of it but unfortunately not working with what seemed to be complicated multi threading issues so I gave up.

Now there is another possibility and that's what Marty is at I think. Since we now have a server app with a REST API interface it is quite possible to build a client side Android app. Then we can see if it would be possible to port the server which would supposedly be simpler but neither Marty or myself have tried it. In any case a client side .apk is already well worth it.

**Comment by f4exb** [comment]
Version after version Android gets more and more useless and becomes just a recreation environment not doing anything really useful. SDRangel will NEVER be supported in Android as it will not support it either. This issue can be closed.

**Comment by f4exb** [comment]
Looks like thanks to @srcejon this one is back!

**Comment by srcejon** [comment]
Now available on Google Play - https://play.google.com/store/apps/details?id=org.sdrangel&hl=en&gl=US

**Comment by tianguo1314** [comment]
Hello, I am very interested in this Android project. May I ask if this SDRangel Android project is open source? Can you provide the SDRangel source code repository address for Android?

**Comment by srcejon** [comment]
This is the repo for it.

**Comment by tianguo1314** [comment]
What I need is a project that can run on AS (Android Studio). The current warehouse project should be a server-side one, right

**Comment by srcejon** [comment]
There isn't one.

**Comment by tianguo1314** [comment]
Can I understand that the Android version of SDRangel is a closed source project

**Comment by srcejon** [comment]
It's built using cmake.

**Comment by f4exb** [comment]
We may consider it implemented now
