### ISSUE TITLE
Is DemodDSD packaged for Fedora?

### ISSUE THREAD

**Issue by Fwappy** [f4exb/sdrangel#1573]
[The Quick Start Page](https://github.com/f4exb/sdrangel/wiki/Quick-start) only mentions Satellite Tracker, DAB Demod, and APT Demod being excluded, but I cannot find `libdemoddsd.so`

**Comment by srcejon** [comment]
No, probably because of the dependency on mbelib. I've updated the Quick Start page.

**Comment by f4exb** [comment]
Maybe mbelib dependency could be made optional. If you have an AMBE key in your system or access to an AMBE server you don't need mbelib. And if you don't have any of these you would not hear any sound but get the control messages. However the dependency tree is a bit complex. I am not even sure if the dependency is in SDRangel or the ancillary DSDcc project.

**Comment by AsciiWolf** [comment]
It would be great if the mbelib dependency was optional. :-) I would like to not ship mbelib in my SDRangel Flatpak (and recommend users to use supported AMBE hardware dongle instead) because of possible legal issues, sadly I have to ship mbelib in order to be able to include the DSD decoder functionality in the Flatpak.
