### ISSUE TITLE
Default Configurations and overwriting them

### ISSUE THREAD

**Issue by fiveseven808** [f4exb/sdrangel#1578]
So I'm pretty new to SDR, and I love that SDRangel has some pre-configured layouts since the software seems a lot more in-depth and complicated than something like sdr#. 

However, while trying to use SDRangel for the first time I accidentally overwrote the one configuration I wanted to use, with a blank workspace/configuration. 

I did a reinstall and I was unable to restore the configuration, and I searched the repo for cfgx files or something so I can restore the configuration I wiped, but I can't find anything. 

I'm at a loss, and I'm a little upset at how easy it was to overwrite a configuration (i.e. without a confirmation). 

I'm requesting that when overwriting anything (I don't know if there are other places in SDRangel as well) to ask the user for confirmation. 

Also, can someone help me get the stock configurations back? 
Thank you.

**Comment by srcejon** [comment]
You should be able to download then from here: https://github.com/f4exb/sdrangel/tree/master/settings/configurations/rtlsdr

 

From: fiveseven808 ***@***.***> 
Sent: 29 January 2023 08:45
To: f4exb/sdrangel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [f4exb/sdrangel] Default Configurations and overwriting them (Issue #1578)

 

So I'm pretty new to SDR, and I love that SDRangel has some pre-configured layouts since the software seems a lot more in-depth and complicated than something like sdr#.

However, while trying to use SDRangel for the first time I accidentally overwrote the one configuration I wanted to use, with a blank workspace/configuration.

I did a reinstall and I was unable to restore the configuration, and I searched the repo for cfgx files or something so I can restore the configuration I wiped, but I can't find anything.

I'm at a loss, and I'm a little upset at how easy it was to overwrite a configuration (i.e. without a confirmation).

I'm requesting that when overwriting anything (I don't know if there are other places in SDRangel as well) to ask the user for confirmation.

Also, can someone help me get the stock configurations back?
Thank you.
