### ISSUE TITLE
Hidden window can'

### ISSUE THREAD

**Issue by chris451gh** [f4exb/sdrangel#1633]
A tuner was set to an FM broadcast station. Run was enabled. SDR at 5msps.
A channel was added, broadcast FM, the one with RDS not WFM. 
It was tuned and adjusted. The (eye) icon was clicked, and this hid the window.
Unable to find a way to unhide it. Clicking the eye again, no effect.
Close the program and restart everything, the phantom window was saved and can't be shown though sound is being demodulated so its still running.
It was in workspace 1 alone. Close empty workspaces and the W1 which appears empty, remains and sound remains running, but without access to the controls or to close it.
Starting another broadcast-fm instance creates an echo. If muted the hidden one is stiii running.  No instructions in wiki how to find a hidden window and set it back to visible.

The program was closed and opened, and there is still a phantom demod running in
window 1 with window0 having the spectrum and frequency of the sampling device.

**Comment by f4exb** [comment]
> Clicking the eye again, no effect

This is not a possible situation once the channel is hidden the (slashed) eye icon disappears with it.

To recover and show all channels attached to a device click on the "show all channels" button in the bottom bar of the device window: https://github.com/f4exb/sdrangel/blob/master/sdrgui/device/readme.md#b2-show-all-channels

**Comment by Abdull** [comment]
A short user story (also for me, because I keep on forgetting how to unhide channels):

"Im hearing white noise sound, but it is not coming from the Pager Demodulator channel, which **apparently** is the only added channel...":

![Image](https://github.com/user-attachments/assets/331166d2-3924-4f8e-9acc-c80bcb79c895)

Clicking on "Display sub windows in tabs", **then clicking through all tabs** will reveal which channels are currently hidden:

![Image](https://github.com/user-attachments/assets/a611e29b-df7f-45f6-81a0-b83f32c2d991)

After clicking on "Show all channels" (in *each* Rx device window?), all previously hidden channels are shown again, including the *SSB Demodulator* channel making noise and the *ADS-B Demodulator* channel I forgot about running in the background:

![Image](https://github.com/user-attachments/assets/0abff8d9-ad1d-426e-bc55-83bafc4d0590)
