### ISSUE TITLE
ADS-B demod: all airline countries are classified as Taiwan

### ISSUE THREAD

**Issue by bczhc** [f4exb/sdrangel#1805]
Hi! I just want to politely ask how the country field is fetched. All of them shows Taiwan, but they shouldn't.

![image](https://github.com/f4exb/sdrangel/assets/49330580/053eb1a4-ceda-40fd-b5bd-4b47ce56396a)

See https://en.wikipedia.org/wiki/List_of_airlines_of_Taiwan; https://en.wikipedia.org/wiki/List_of_airlines_of_China

**Comment by srcejon** [comment]
There's a file (demodadsb/flags/regprefixmap.csv) that maps aircraft registration prefixes to the flag.

Looking at it, we have a clash, in that both China and Taiwan both have the prefix B, with nothing to distinguish the two) - and Taiwan is last in the file, so that's why you get the Taiwan flag.

Can you perhaps add another screenshot showing the registration column, so I can see if there's any more info that we could perhaps use?

**Comment by srcejon** [comment]
Ok, it seems China should have B-4 digits, and Taiwan B-5 digits, so I may be able to add some additional logic to check for that.

**Comment by bczhc** [comment]
Yes. As this: 
![image](https://github.com/f4exb/sdrangel/assets/49330580/eb19df3a-7d00-410a-8553-4f5226ec1516)
That makes sense. Thanks!

**Comment by srcejon** [comment]
Have added a patch - let me know if you still see problems.

**Comment by bczhc** [comment]
Alright. Seems to be OK:
![image](https://github.com/f4exb/sdrangel/assets/49330580/c1122f80-4be7-4b4e-8cd3-8aeed7217d97)

BTW why use the CPC flag but not its national flag? 🤔

**Comment by srcejon** [comment]
I just used a flag icon pack from here (https://radarspotting.com/forum/index.php?action=gallery;cat=33). If you have a correct 40x20 pixel image, I can replace it.

**Comment by bczhc** [comment]
Oh okay. Actually I have no idea on this, maybe in this case CPC is at the same hierarchy with Hong Kong and Macau (they are Special Administrative Regions)... Just leave it so. Thanks again and this issue can be marked as solved.
