### ISSUE TITLE
Improve key morse in ssb modulator

### ISSUE THREAD

**Issue by internetuser22** [f4exb/sdrangel#1948]
suggestion ability to manually key with a straight key, by com port or mouse

**Comment by f4exb** [comment]
These controls do exist: check under the "WPM" button (it is not in the main screenshot) Look at 16.7 to 16.10 under here https://github.com/f4exb/sdrangel/tree/master/plugins/channeltx/modssb#166-text-playstop 

To use a hardware key you will need another program to be able to generate keystrokes.

**Comment by f4exb** [comment]
It turns out that the easier way to interface a morse key to a computer is to recycle a mouse by connecting the right and left buttons to the iambic keys (for iambic) or just one of them for a straight key. Mouse control is not implemented and it would be an improvement if was.

More importantly a sound feedback should be linked to the keys. It is not possible to use the radio feedback because of the delay.

**Comment by f4exb** [comment]
With the present design of audio control it does not seem possible to avoid a slight delay on audio. So even when activating the audio feedback this delay is still annoying when keying directly with the mouse. Therefore I think a CW keyer with a buzzer for audio feedback is necessary while using the straight key mode in the SSB modulator.
