### ISSUE TITLE
Implemented in 7.20  Map feature can export data to KML files. 

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#2071]
Implemented in 7.20 
Map feature can export data to KML files. Implements AIS and ADSB decoders: improvement proposal #1068
Enhancement request, can you provide a real-time KML feed to power a related application ?

**Comment by srcejon** [comment]
KML export was implemented via Cesium, which doesn't support real-time export.

This is similar to #2012

**Comment by alphafox02** [comment]
I figured there’s something telling cesium where to plot, couldn’t those same functions be where “CoT” is optionally introduced in order to populate an external map or rather a TAK server which would in turn populate numerous maps depending on how the TAK server is configured.

Here is an example in C++
https://github.com/chipbrommer/COT_Utility

**Comment by srcejon** [comment]
Either can be done, but I have a long list of other stuff to do first, I'm afraid.

**Comment by alphafox02** [comment]
Totally understand. Awesome work you all are doing.
