### ISSUE TITLE
Build for windows / DATV mod and Demod

### ISSUE THREAD

**Issue by RenePE9R** [f4exb/sdrangel#222]
I am trying to follow the instructions to make an windows build incl de DATV plugins.
I learned that more Libs are necessary than described, but the systems hangs at this moment at the BladeRF libraries. 
Many errors occur.
Maybe an newer version is used at this moment?
Or is it possible to make an build for the pluggins without building the complete project?

**Comment by f4exb** [comment]
BladeRF has nothing to do with the DATV mod and demod. You may run into other issues because of dependency on OpenCV.

LibbladeRF code has changed a lot since version 2 and is not compatible with the code still present on SDRangel master branch. I think it still refers to version 1.5.1 The present dev branch has the code to compile with libbladeRF v.2 and the plugins for BladeRF 2.0 micro.

To build for Windows you will need to build libbladeRF separately with CMake GUI and Mingw32 and use it as an external library. This is not for the faint hearted. Lot of things do not work out of the box and you will need to make some code changes to libbladeRF to be able to compile with the Mingw32 toolchain.

I managed to build the plugins for BladeRF classic (v1) and Micro (v2) but they are untested at the moment.

If you do not need BladeRF support I suggest to skip this part completely.
