### ISSUE TITLE
Presets backup/restore. Enhance REST API for presets.

### ISSUE THREAD

**Issue by i-am-tof** [f4exb/sdrangel#241]
Hello,

A backup function would be a great addition to save all groups and presets at once.
I would know where the "save the current settings (inc. presets)" button store its result.
I use sdrangel v4.2.4 on Ubuntu Xenial 16.04.

**Comment by i-am-tof** [comment]
I saw for one preset at a time, but sadly it doesn't save belonging group.
Rebuilding presets manually will become more and more boring with time, and I especially need to backup and to replicate, just as you told.

Awaiting this enhancement, in which file(s) does sdrangel stores its settings+presets ?

**Comment by f4exb** [comment]
The missing belonging group is intentional because when you export and import presets one at a time you do not necessarily want to recreate them in the same group.

Presets use the Qt preferences mechanism for storage so this is system dependent. On Linux systems this is in `~/.config/f4exb/SDRangel.conf` data is binary base64 encoded so although it is ASCII this is effectively humanly unreadable.

**Comment by i-am-tof** [comment]
Thank you.

**Comment by beta-tester** [comment]
> On Linux systems this is in ~/.config/f4exb/SDRangel.conf data is binary base64 encoded so although it is ASCII this is effectively humanly unreadable.

where is it stored on a windows machine?

**Comment by f4exb** [comment]
I've found a way to retrieve it with Qt interface: http://doc.qt.io/qt-5/qsettings.html#fileName Since this is a recurring question I will add a message in the log and in the about panel also.

For readibility and edit of the presets maybe the best option is to implement it via REST API. At the moment interaction with presets using REST API is rudimentary.

**Comment by f4exb** [comment]
As you mentioned on Windows this is stored in the registry and I think that the regedit utility can export and import keys:

![image](https://user-images.githubusercontent.com/6192319/51322404-a7c16800-1a65-11e9-9ad0-9e52fd36bfbd.png)

**Comment by beta-tester** [comment]
yes, now i know that next time i will export the registry key on windows. ;-)
but that way you can not transfere presets from windows to linux or from linux to windows.
anyhow, first i have to go the long way to restore all my frequency presets...
hopefully i can find all the frequencies i had in the past...
how was it... no backup, no pity... :-D

**Comment by f4exb** [comment]
Going through REST API you could even transfer live between two running applications over the network.

**Comment by beta-tester** [comment]
Thank you, that despite my obtuseness, you still have not given up to help me ...
i just found the REST API with its documentation in SDRangel you mentioned.
http://127.0.0.1:8091 ...
oops, how could i overlook its existence?
now i have to study you well documeted REST API of SDRangel.
there are also examples for different programming languages... very nice.

**Comment by f4exb** [comment]
You will see that there is not much yet for the presets: just transposing what you can do with the GUI.  The purpose of implementing this ticket would be to enrich it so as to be able to deal with presets and settings generally in JSON format.

**Comment by f4exb** [comment]
Implemented in v4.11.6: /sdrangel/config with GET, PUT, PATCH methods
