### ISSUE TITLE
ERROR / This application failed to start because no Qt platform...

### ISSUE THREAD

**Issue by F4GXS** [f4exb/sdrangel#415]
Hello Edouard, I have just installed your SDRAngel software on my PC to be able to use it with my HackRF One, I tried to start it and I got an error message, here it is

_"sdrangel : This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugin are: direct2d, windows."_

So, I reinstalled the software as shown and I still have the same error, no way to start the software.

What is happening ? do you have an idea ?

73 de F4GXS Pierre

**Comment by f4exb** [comment]
Firstly please express yourself in English as this is an international community and English is likely to be understood by most of us.

Secondly "This application failed to start because no Qt platform plugin could be initialized" should be a clear enough message so you need to sort out issues with Qt support on your machine first. "Available platform plugin are: direct2d, windows." may suggest this is an issue with graphics. On Windows Qt uses the so called "Angle" for OpenGL support that uses DirectX in the background.

**Comment by F4GXS** [comment]
OK

Firstly, I still do not understand where the problem comes from, you tell me that I have to sort out issues with "Qt" support, that's why I ask you how to help me to do that, me and the "Qt" it is not my cup of tea.

Secondly, I think my laptop is from a different age, it still runs under Vista.

**Comment by f4exb** [comment]
Qt is none of my business. I am also a Qt user.

**Comment by F4GXS** [comment]
business is business.
alright, leave it, i'm go to update my Vista laptop to W10.

Thanks
