### ISSUE TITLE
Saving a bookmark does not work if only the modulation changes

### ISSUE THREAD

**Issue by febs** [f4exb/sdrangel#446]
Linux, git commit acd08925368ba1ee2f35469314abdc4dea02a1fe (v 4.12.1).

How to reproduce it:
* Create a bookmark.
* Then add a demodulation plug-in.
* Press save.
* Reload the bookmark and it was as before saving the changes.

Thanks,

**Comment by f4exb** [comment]
You do not understand how this works although the term "bookmark" does give an idea because it behaves a little bit like browser bookmarks. However this is called "presets". So when you "save" presets you save the whole bunch of presets to disk including the current configuration on R0. So "save" is irrelevant in your scenario, This is what actually happens:
- "create a bookmark": this creates a preset without demodulator (your current state)
- "add demodulation plugin": this adds a demod to your device set (nothing has changed for the preset)
- "save": this saves all presets including the empty one (no demod) you just created
- "reload the bookmark": the preset is still empty and this is what you see

What you are looking for is "update preset" (the cycle arrow - second icon from the left) after you have added the demodulator.

**Comment by febs** [comment]
Thanks for the explaination.
