### ISSUE TITLE
Audio Input gets stuck after stopping and restarting transmission

### ISSUE THREAD

**Issue by ThomasTheGerman** [f4exb/sdrangel#470]
I set the Audio Input to either my microphone the pulseaudio monitor device, start transmitting, and get a clean signal that sounds great. 
Then I stop transmitting and start again, and the result is no proper signal at all, just a buzzing sound with regular clicking/popping. 
Disabling the audio input, switching around audio devices and starting/stopping transmission again gets rid of the problem, until I stop transmitting again.

If I first disable the audio input, then stop transmitting, the issue doesn't appear. Only if transmission is stopped while audio is being played back. 

Maybe it's an issue with the buffer still containing audio samples that haven't been transmitted yet, and it doesn't get cleared properly when the transmission is restarted? The noise is just a couple samples being repeated over and over. I've been able to reproduce it with different modulators and sinks selected.
![image](https://user-images.githubusercontent.com/18717919/73304352-60dd8500-4218-11ea-953a-08325a7257f5.png)

System info: Arch, Pulseaudio 13.0, SDRAngel 4.13.0 compiled a couple hours ago.

**Comment by f4exb** [comment]
For some reason this commit: https://github.com/f4exb/sdrangel/commit/583a144c67c71208c2edcd251904902ecd372c15 is causing more trouble than it is supposed to solve. It has to be fallen back.

**Comment by f4exb** [comment]
Reverting the commit does not change anything. In fact the issue happens when the system default device is selected down in the list of devices. This device is marked with an "S" in the prefix column:

![audioinput_select](https://user-images.githubusercontent.com/6192319/73597448-5ed33900-452c-11ea-993b-bf0c0f7ef797.png)

If you want to use the default device just leave the "System default device" selected at the top of the list which is in fact the default.

**Comment by f4exb** [comment]
question has been answered
