### ISSUE TITLE
HELLO I WANT TO KNOW THAT MAKES THE FUNCTION

### ISSUE THREAD

**Issue by gaspar1987** [f4exb/sdrangel#529]
![image](https://user-images.githubusercontent.com/13591469/83294977-89898180-a1ee-11ea-90e2-3a0d3f1989d8.png)
HELLO I WANT TO KNOW THAT MAKES THE FUNCTION

**Comment by f4exb** [comment]
Please use sensible case in the title and express yourself correctly to be understandable

**Comment by gaspar1987** [comment]
Hello I wanted to know if it worked to enlarge the frames or reduce them to
any small little cuckoo I could set it to 200 s I do not know if it's
seconds or stuff I do not understand and I would like to know what is used
to listen to trams or listen to analog.n

**Comment by f4exb** [comment]
Sorry this is still not clear...
  - what "frames" are you talking about?
  - what the heck is that "little cuckoo"?!
  - "S/s" stands for samples per second this is a sampling rate unit compatible with Hertz (Hz) but more expressive in this case. If you hover on the control the tooltip will give you more details (same thing on all controls on the GUI).
  - " I would like to know what is used to listen to trams or listen to analog.n": what does this mean really?

If your question is "Can I get a lower sampling rate than 230 kS/s on the RTL-SDR" then the answer is "no" because this is a hardware limitation.

**Comment by f4exb** [comment]
This can be closed
