### ISSUE TITLE
Feature request AppImage

### ISSUE THREAD

**Issue by ntoulasd** [f4exb/sdrangel#697]
Would you provide AppImage executables ?
There are more easy to run them in different environments.
Last time I try to compile at Ubuntu 18.04 I got an error about an older than required lib.
More at https://appimage.org/

Thanks

**Comment by f4exb** [comment]
This has been asked for and dealt with before and I will not provide artifacts other than those provided in the releases section. 

Ubuntu 18.04 is outdated since cmake requirements is now v3.10 so you cannot get very far.

Plese comply with the rules [here](https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux)
