### ISSUE TITLE
Other color themes

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#963]
Is it possible to provide other color themes , especially for the scroll bars, they are sometimes difficult to distinguish or semi-darkness : gray on gray :( ?

**Comment by f4exb** [comment]
> gray on gray :( ?

If you check carefully they are not exactly the same grays. 

Anyway, yes I suppose this would be possible but requires a lot of efforts mostly because in many places the background of some widgets is hardcoded with a `RGB = (79, 79, 79)` kind of gray using stylesheets. Of course this makes it fairly easy to spot in a global search but then one would have to recode everything dynamically and this happens in many places.

Today the "theme" (style and palette in Qt terms) are defined in the startup code in `app/main.cpp` so firstly it depends if this code can be moved to the `MainWindow` so that it can be changed dynamically or at least be saved and restored from the default preset.
